import re

with open('F:\\吉胡阿川\\01lhjk\\事业\\AXS设计工作室\\AXS_设计工作室客户需求深度调研表.html', 'r', encoding='utf-8') as f:
    text = f.read()

replacements = [
    ('AXS סȿ̽?(?', 'AXS 客户深度需求探测引擎'),
    ('AXSAesthetics  System  ϵͳ?/div>', 'AXS Aesthetics System | 物理探测系统</div>'),
    ('<h1>AXS 蹤?/h1>', '<h1>AXS 客户需求深度探测引擎</h1>'),
    ('<strong>ϵͳмµ ʵ ?ϵͳĴ?գΪۼط?/strong>', '<strong>系统声明：抛弃感性的审美黑话，通过物理参数的无情拷问，将您的需求强制映射为可落地的建筑矩阵。</strong>'),
    ('<strong>?ţ</strong>', '<strong>[ 探测协议开启 ]</strong>'),
    ('A?36 BÿӵϸڣԤҪռ 15-20 ӵʱ?br>', '包含 36 项核心参数拷问，预估耗时 15-20 分钟。<br>'),
    ('ǰƣţһ軣𣬴￪ʼǁB¶ȵı?', '请放松心情如实填写，由此开启一场深度剖析的旅程。'),
    ('01. ס', '01. 人口底座'),
    ('ģ 01 | ˿ڵ?/div>', '模块 01 | 物理与人口底座</div>'),
    (' / Ů?>', '先生 / 女士">'),
    ('֮?/ ƽ?/ 150ƽ', '小区名称 / 建筑面积 / 例: 150平">'),
    ('˾̻ͼֳͼCAD ͼֻƽͼ?/span>', '开发商户型图 / 现场测绘图 / CAD 原始图 / 干净的平面图</span>'),
    ('4. ͻ户型图文件', '4. 客户意向设计图文件'),
    ('˾ϲĿռͼͼװͼ?/span>', '您喜欢的空间意向图 / 效果图 / 局部软装图</span>'),
    ('5. Ԥƾ߷Χ?/span>', '5. 预算控制绝对红线？</span>'),
    ('ϵͳϸ߾SװԵ?/span>', '系统将严格依据该红线约束后续的设计演进。</span>'),
    ('15-30?(޿ؼۣ?</label>', '15-30万 (极限控制)</label>'),
    ('30-50?(?</label>', '30-50万 (常规品质)</label>'),
    ('50-80?(߶?</label>', '50-80万 (高品质)</label>'),
    ('80?(e?</label>', '80万以上 (上不封顶)</label>'),
    ('6. ͥסԱɼ?/span>', '6. 家庭常住人员与结构？</span>'),
    ('޶?+ 1??+ ż˾ס', '夫妻 + 1个小孩 + 偶尔老人同住'),
    ('7. ˳ʱ?/span>', '7. 男主人出生日期/时间？</span>'),
    ('ںϷˮ׾ȴͳռο粻G?/span>', '用于风水磁场计算与空间传统参考（选填）</span>'),
    ('8. Ů˳ʱ?/span>', '8. 女主人出生日期/时间？</span>'),
    ('9. ?/span>', '9. 宠物豢养情况？</span>'),
    ('?> ޳?/label>', '无宠物</label>'),
    ('?> èԤeλ</label>', '猫 / 狗 (预留独立位置)</label>'),
    ('?> </label>', '其他宠物</label>'),
    ('10. ס?Ů˾(cm)Ҫ?/span>', '10. 主操作者身高(cm)与惯用手？</span>'),
    ('߶ȻܣƳߵ̨ϴߵĆ?/span>', '影响全屋定制高度、厨房台面高度、洗手台高度等</span>'),
    ('175cm / ?60cm / ŮƲ', '175cm / 习惯右手'),
    ('02. ռ滮', '02. 空间规划'),
    ('ģ 02 | ռ滮?/div>', '模块 02 | 空间规划与功能分配</div>'),
    ('空间 04?3ǷҪڴλ⹦?/span>', '空间 04 次卧 3：是否需要固定床位？</span>'),
    ('ѡʵ?/span>', '多选：请勾选主卧需要的核心功能</span>'),
    ('}?> }?/label>', '独立卫浴</label>'),
    ('ñ?> ñ?/label>', '书桌/梳妆台</label>'),
    ('?> ?/label>', '阳台/休闲区</label>'),
    ('ѡǰͳʹ÷ʽѡ?/span>', '多选：请明确次卧 1 的主要使用对象</span>'),
    ('鷿?> 鷿?/label>', '长辈房</label>'),
    ('ѡʺϱﵯ?/span>', '多选：请明确次卧 2 的空间属性</span>'),
    ('ûԣѡ޴˿ռ?/span>', '多选：如果没有次卧 3 可不填</span>'),
    ('ѡжϿҾߡɺ͵λ?/span>', '多选：客厅主要承载的活动</span>'),
    ('ѡжϲͳߡԴ?/span>', '多选：餐厅主要承载的活动</span>'),
    ('ѡжϳߡ̨߶?/span>', '多选：厨房的核心需求</span>'),
    ('̨?> ̨?/label>', '双操作台</label>'),
    ('˫??> ˫??/label>', '双开门大冰箱</label>'),
    ('ϴ?> ϴ?/label>', '洗碗机</label>'),
    ('ˮϵ?> ˮϵ?/label>', '全屋净水</label>'),
    ('ѡжυf뷽ʽ?/span>', '多选：卫浴核心需求</span>'),
    ('˫̨?> ˫̨?/label>', '双台盆</label>'),
    ('/?> /?/label>', '独立淋浴房/浴缸</label>'),
    ('ǿ?> ǿ?/label>', '强力排风/暖风机</label>'),
    ('ѡҲΪ뻧?/span>', '多选：入户玄关核心需求</span>'),
    ('Ь?> Ь?/label>', '换鞋凳</label>'),
    ('߯?> ߯?/label>', '家政/次净衣柜</label>'),
    ('䳾?> 䳾?/label>', '全身穿衣镜</label>'),
    ('ѡ̨ʵ?/span>', '多选：阳台核心需求</span>'),
    ('ѡж顢λͰ̶?/span>', '多选：书房核心需求</span>'),
    ('ѡжϷΧߺ?/span>', '多选：休闲区核心需求</span>'),
    ('ѡжϼɺ?/span>', '多选：储物/家政核心需求</span>'),
    ('ٶǽ"> ٶǽ壬ԭͻ?/label>', '尽量少砸墙"> 尽量少砸墙，保持原格局</label>'),
    ('?> ϣάи</label>', '绝不砸墙"> 绝不砸墙，希望维持现状</label>'),
    ('03. 鶯', '03. 动线与习惯'),
    ('ģ 03 | 䳾Ҷ?/div>', '模块 03 | 归家动线与生活习惯</div>'),
    ('ѡжɡºλ?/span>', '多选：归家后物品放置习惯</span>'),
    ('عҹ/?> عҹ/?/label>', '挂衣区/包包</label>'),
    ('ѡжʱ̨桢ද?/span>', '多选：拆快递/处理外卖的习惯</span>'),
    ('ѡжϹ黺͵άɱ?/span>', '多选：归家后的行为路径</span>'),
    ('Ȼϴ?> Ȼϴ?/label>', '先去洗漱</label>'),
    ('ʽ¹ܣһҳ 100% ţ?50% GƵ?/span>', '下沉式玄关可以有效阻挡灰尘，但有轻微台阶</span>'),
    ('ǿ?> ǿ?/label>', '强烈希望做下沉</label>'),
    ('Ҫϰݵƽ?> Ҫϰݵƽ?/label>', '不需要，习惯地面全平</label>'),
    ('<!-- ================= ģ 04LDK?================= -->', '<!-- ================= 04. LDK与隐蔽机电黑盒 ================= -->'),
    ('04. ?/span>', '04. LDK与机电</span'),
    ('05. ?/span>', '05. 卫浴撕裂</span'),
    ('07. Ը', '07. 视觉与未来演进'),
    ('06. ȡ', '06. 代谢系统'),
    ('</label>\n                    <label class="option-label"><input type="checkbox" name="space_master_bedroom" value=""> </label>', '</label>'),
    ('<label class="option-label"><input type="checkbox" name="space_secondary_bedroom_3" value=""> </label>', ''),
    ('<label class="option-label"><input type="checkbox" name="space_balcony" value=""> </label>', ''),
    ('<label class="option-label"><input type="checkbox" name="space_leisure_area" value=""> </label>', ''),
    ('<label class="option-label"><input type="checkbox" name="space_storage_housekeeping" value=""> </label>', ''),
    ('<label class="option-label"><input type="checkbox" name="genkan_drop" value=""> </label>', ''),
    ('<label class="option-label"><input type="checkbox" name="delivery_area" value=""> </label>', ''),
    ('value="?>', 'value="其他">')
]

for old, new in replacements:
    text = text.replace(old, new)

with open('F:\\吉胡阿川\\01lhjk\\事业\\AXS设计工作室\\AXS_设计工作室客户需求深度调研表.html', 'w', encoding='utf-8') as f:
    f.write(text)

print('File thoroughly scrubbed and restored!')
